rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: True

publish_dry_run: True

topology_path: topology.yaml

schema_blacklist:
    - information_schema
    - mysql
    - performance_schema
    - test

# biz and employee_new is for acceptance tests
table_whitelist:
    - biz
    - employee_new
    - advertiser
    - business_payment_account_entity
    - payment_account_entity
    - payment_feature
    - payment_program
    - replication_heartbeat
    - salesperson

producer_name: replication_handler

team_name: bam

zookeeper_discovery_path: '/nail/etc/zookeeper_discovery/generic/local.yaml'

pii_yaml_path: '/nail/etc/services/database_pii'

recovery_queue_size: 2000

module_config:
    -   namespace: yelp_conn
        file: /nail/srv/configs/yelp_conn_generic.yaml
        initialize: yelp_conn.initialize
        config:
            connection_set_file: connection_sets.yaml

            connection_wrappers:
                - yelp_conn.sqllogger.LoggingConnectionWrapper
                - yelp_conn.wrappers.AnnotatingConnectionWrapper

            query_logging_listeners:
                - ['yelp_conn.sqllogger.ClogCursorListener', 'tmp_query_log']

            # Log queries to all listeners in `query_logging_listeners`
            enable_query_logging: True
            # Print queries to stdout
            enable_query_printing: True

    -   namespace: clog
        initialize: yelp_servlib.clog_util.initialize
        config:
            log_stream_name: tmp_replication_handler_logs
        file: /nail/srv/configs/clog.yaml

    - namespace: smartstack_services
      file: /nail/etc/services/services.yaml

    - namespace: data_pipeline
      config:
        load_schematizer_host_and_port_from_smartstack: True
        kafka_cluster_type: datapipe
        kafka_cluster_name: uswest2-devc
        skip_messages_with_pii: True
        kafka_producer_buffer_size: 500
