module_config:
    -  namespace: cluster_config
       config:
           cluster: docker_testing_cluster
           source_replica:  replication_handler_source
           schema_tracking_replica: replication_handler_schema_tracker
