changelog_namespace: changelog.itest.v2

changelog_mode: True

namespace: dev_changelog

rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: False

publish_dry_run: False

disable_sensu: True

topology_path: /nail/srv/configs/topology.yaml

resume_stream: False

container_name: itest_changelog

container_env: docker-compose

force_exit: True
module_env_config:
    - namespace: data_pipeline
      config:
        load_schematizer_host_and_port_from_smartstack: True
        kafka_cluster_type: datapipe
        kafka_cluster_name: uswest2-devc
        skip_messages_with_pii: False
        kafka_producer_buffer_size: 500
