replication_database:
    -  namespace: replication_database
       config:
           host: dbmaster
           port: 3306
           user: 'yelpdev'
           passwd: ''

schema_tracking_database:
    -  namespace: schema_tracking_database
       config:
           host: 169.254.1.128
           port: 3306
           user: 'yelpdev'
           passwd: ''

zookeeper:
    -  namespace: zookeeper
       config:
           host: '10.10.0.0'
           port: 2181
