rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: True

publish_dry_run: True

topology_path: /nail/srv/configs/topology.yaml

module_env_config: []
