rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: False

publish_dry_run: False

topology_path: /nail/srv/configs/topology.yaml

schema_blacklist:
    - information_schema
    - mysql
    - performance_schema
    - test

module_env_config: []
