replication_database:
    -  namespace: replication_database
       config:
           host: dbmaster
           port: 3306
           user: 'yelpdev'
           passwd: ''

schema_tracking_database:
    -  namespace: schema_tracking_database
       config:
           host: dblocal 
           port: 3306
           user: 'yelpdev'
           passwd: ''

zookeeper:
    -  namespace: zookeeper
       config:
           host: zkhost
           port: 2181
