replication_database:
    -  namespace: replication_database
       config: 
           host: '169.254.0.165'
           port: 3306
           user: 'yelpdev'
           passwd: ''

zookeeper_storage:
    -  namespace: zookeeper
       config:
           host: '10.10.0.0'
           port: 2181
