replicationhandler:
  build: .
  image: $DOCKER_TAG
  links:
    - kafka
    - zookeeper:zk
    - rbrsource
    - schematracker
    - rbrstate
    - schematizer
  volumes_from:
    - replicationhandlerconfigs
  command: /code/virtualenv_run/bin/pypy /code/replication_handler/batch/parse_replication_stream.py
  environment:
    - SERVICE_ENV_CONFIG_PATH=config-env-itest-opensource.yaml
    - FORCE_AVOID_INTERNAL_PACKAGES=True
replicationhandlerconfigs:
  build: acceptance/configs/
# Replication Handler databases
rbrsource:
    build: devdbs/rbr_source/
schematracker:
    build: devdbs/schema_tracker/
rbrstate:
    build: devdbs/rbr_state/

kafkadiscoveryconfigs:
  image: docker-dev.yelpcorp.com/kafka-discovery-configs-testing:latest
