replicationhandler:
  build: .
  image: $DOCKER_TAG
  links:
    - kafka
    - zookeeper:zk
    - rbrsource
    - schematracker
    - rbrstate
    - schematizer
  volumes_from:
    - replicationhandlerconfigs
  command: /code/virtualenv_run/bin/pypy /code/replication_handler/batch/parse_replication_stream.py -vv --no-notification
  environment:
    - SERVICE_ENV_CONFIG_PATH=config-env-itest.yaml
replicationhandleropensource:
  build: .
  image: $DOCKER_TAG
  links:
    - kafka
    - zookeeper:zk
    - rbrsource
    - schematracker
    - rbrstate
    - schematizer
  volumes_from:
    - replicationhandlerconfigs
  command: /code/virtualenv_run/bin/pypy /code/replication_handler/batch/parse_replication_stream.py -vv --no-notification
  environment:
    - SERVICE_ENV_CONFIG_PATH=config-env-open-itest.yaml
replicationhandlerchangelog:
  build: .
  image: $DOCKER_TAG
  links:
    - kafka
    - zookeeper:zk
    - rbrsource
    - schematracker
    - rbrstate
    - schematizer
  volumes_from:
    - replicationhandlerconfigs
  command: /code/virtualenv_run/bin/pypy /code/replication_handler/batch/parse_replication_stream.py -vv --no-notification
  environment:
    - SERVICE_ENV_CONFIG_PATH=config-env-changelog-itest.yaml
replicationhandlerconfigs:
  build: acceptance/configs/
# Replication Handler databases
rbrsource:
    build: devdbs/rbr_source/
schematracker:
    build: devdbs/schema_tracker/
rbrstate:
    build: devdbs/rbr_state/
